version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db-data:/var/lib/mysql
  hubbackend:
    depends_on:
      - mariadb 
    image: miasdocker/studenthub:hubbackend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mariadb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    network_mode: host
  client:
    stdin_open: true
    image: miasdocker/studenthub:client
    volumes:
      - /app/node_modules
      - ./StudentHub:/app
volumes: 
  db-data:
